sequential: sieve.cpp
	g++ sieve.cpp -o sequential -std=c++11 -Wall -Wextra -pedantic

pthreads: sieve_pthreads.cpp
	g++ sieve_pthreads.cpp -o pthreads -std=c++11 -pthread -Wall -Wextra -pedantic

openmp: sieve_openmp.cpp
	g++ sieve_openmp.cpp -o openmp -std=c++11 -Wall -Wextra -fopenmp -pedantic
