sequential: Game_Of_Life.c
	gcc Game_Of_Life.c -o sequential -std=c11 -Wall -Wextra -pedantic

openmp: Game_Of_Life_OpenMP.c
	gcc Game_Of_Life_OpenMP.c -o openmp -std=c11 -Wall -Wextra -fopenmp -pedantic
